# Generated by Django 4.2.19 on 2025-02-26 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergame', '0002_remove_usergame_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
