# Generated by Django 4.2.19 on 2025-02-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergame', '0003_alter_usergame_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergame',
            old_name='status',
            new_name='game_status',
        ),
        migrations.AddField(
            model_name='usergame',
            name='page_status',
            field=models.CharField(choices=[('collection', 'Collection'), ('wishlist', 'Wishlist')], default='wishlist', max_length=50),
        ),
    ]
