# Generated by Django 4.2.19 on 2025-02-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('cover', models.URLField()),
                ('summary', models.TextField()),
                ('first_release_date', models.DateTimeField()),
                ('total_rating', models.FloatField()),
                ('total_rating_count', models.IntegerField()),
                ('genres', models.JSONField()),
                ('rating', models.FloatField()),
                ('age_ratings', models.JSONField()),
                ('storyline', models.TextField()),
            ],
        ),
    ]
