# Generated by Django 4.2.19 on 2025-02-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_platform_remove_game_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_release_date',
            field=models.DateField(),
        ),
    ]
