# Generated by Django 4.2.19 on 2025-02-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_first_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='age_ratings',
        ),
    ]
