# Generated by Django 4.2.19 on 2025-02-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='storyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
