# Generated by Django 4.2.19 on 2025-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_cover_alter_game_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
